name: locate_me
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

scripts:
  generate_files: flutter pub run build_runner build --delete-conflicting-outputs
  load_language_resource: flutter pub run easy_localization:generate --source-dir ./assets/translations
  generate_language_key: dart run easy_localization:generate -f keys -o locale_keys.g.dart --source-dir ./assets/translations
  generate_app_icon: dart run flutter_launcher_icons:main
  generate_icon_pack: dart run flutter_iconpicker:generate_packs --packs allMaterial

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  font_awesome_flutter:
  go_router: ^14.2.3
  flutter_rating_bar: ^4.0.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  app_settings: ^5.1.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  hooks_riverpod: ^2.5.1
  # flutter_config: ^2.0.2
  uuid: ^4.4.0
  carousel_slider: ^5.0.0
  drift_sqlite_async: ^0.1.0-alpha.1
  path_provider: ^2.1.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.21
  path: ^1.9.0
  flutter_map: ^7.0.2
    # path: dependency_overrides/flutter_map

  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  widget_to_marker: ^1.0.5
  flutter_screenutil: ^5.9.3
  # camera: ^0.11.0+1
  intl: ^0.19.0
  easy_localization: ^3.0.7
  shamsi_date: ^1.0.2
  share_plus: ^10.0.0
  file_picker: ^8.0.5
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  flutter_hooks: ^0.20.5
  flutter_iconpicker: ^4.0.1
  flutter_colorpicker: ^1.1.0
  # flutter_launcher_icons: ^0.14.1
  map_launcher: ^3.3.1
  # camerawesome: ^2.0.1
  image_picker: ^1.1.2
  skeletonizer: ^1.4.1+1
  flutter_dotenv: ^5.1.0
  adivery: ^4.2.0
  plugin_platform_interface: ^2.1.8
  supabase_flutter: ^2.8.0
  # supabase_auth_ui: ^0.5.2
  # mapbox_maps_flutter: ^2.2.0
  # mapbox_maps_flutter: ^2.2.0
  # flutter_polyline_points: ^2.1.0


flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  drift_dev: ^2.18.0
  mockito: ^5.0.16
  riverpod_test: ^0.1.6
  path_provider_platform_interface: ^2.1.2
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/category/
    - assets/background/
    - assets/translations/
    - assets/logo/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSansMobile
      fonts:
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile.ttf
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile-Black.ttf
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile-Bold.ttf
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile-Light.ttf
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile-Medium.ttf
        - asset: assets/fonts/iran_sans/IRAN-Sans-Mobile-UltraLight.ttf


    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir/Vazir-Bold-FD-WOL.ttf
        - asset: assets/fonts/Vazir/Vazir-Bold.ttf
        - asset: assets/fonts/Vazir/Vazir-FD-WOL.ttf
        - asset: assets/fonts/Vazir/Vazir-Light-FD-WOL.ttf
        - asset: assets/fonts/Vazir/Vazir-Light.ttf
        - asset: assets/fonts/Vazir/Vazir-Medium-FD-WOL.ttf
        - asset: assets/fonts/Vazir/Vazir-Medium.ttf
        - asset: assets/fonts/Vazir/Vazir-Thin-FD-WOL.ttf
        - asset: assets/fonts/Vazir/Vazir-Thin.ttf
        - asset: assets/fonts/Vazir/Vazir.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
