// Mocks generated by Mockito 5.4.4 from annotations
// in locate_me/test/features/home/repository/locations_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:locate_me/features/home/model/place_item_model.dart' as _i4;
import 'package:locate_me/features/home/repository/locations_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeScreenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeScreenRepository extends _i1.Mock
    implements _i2.HomeScreenRepository {
  @override
  _i3.Future<List<_i4.PlaceItemModel>> getLocations() => (super.noSuchMethod(
        Invocation.method(
          #getLocations,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.PlaceItemModel>>.value(<_i4.PlaceItemModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.PlaceItemModel>>.value(<_i4.PlaceItemModel>[]),
      ) as _i3.Future<List<_i4.PlaceItemModel>>);

  @override
  _i3.Future<_i3.Stream<List<_i4.PlaceItemModel>>> watchLocationList() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchLocationList,
          [],
        ),
        returnValue: _i3.Future<_i3.Stream<List<_i4.PlaceItemModel>>>.value(
            _i3.Stream<List<_i4.PlaceItemModel>>.empty()),
        returnValueForMissingStub:
            _i3.Future<_i3.Stream<List<_i4.PlaceItemModel>>>.value(
                _i3.Stream<List<_i4.PlaceItemModel>>.empty()),
      ) as _i3.Future<_i3.Stream<List<_i4.PlaceItemModel>>>);

  @override
  _i3.Future<_i4.PlaceItemModel?> getLocation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [id],
        ),
        returnValue: _i3.Future<_i4.PlaceItemModel?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.PlaceItemModel?>.value(),
      ) as _i3.Future<_i4.PlaceItemModel?>);

  @override
  _i3.Future<void> deleteLocation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateFavoriteStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #updateFavoriteStatus,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
